import type { MockUser, RecipeDetail } from '../../types';

export const MOCK_RECIPES: RecipeDetail[] = [
  {
    id: 101,
    title: 'Garlic Soy Chicken Rice Bowl',
    image: 'https://picsum.photos/400/300?random=101',
    readyInMinutes: 25,
    servings: 2,
    missedIngredientCount: 0,
    usedIngredientCount: 5,
    sourceUrl: null,
    ingredients: [
      { name: 'Chicken', amount: 250, unit: 'g' },
      { name: 'Rice', amount: 1, unit: 'cup' },
      { name: 'Garlic', amount: 2, unit: 'cloves' },
      { name: 'Soy Sauce', amount: 2, unit: 'tbsp' },
      { name: 'Olive Oil', amount: 1, unit: 'tbsp' },
    ],
    instructions: [
      'Cook rice according to package instructions and keep warm.',
      'Slice chicken and season lightly with salt and pepper.',
      'Heat olive oil in a pan, then cook chicken until browned.',
      'Add minced garlic and soy sauce, stir for 1-2 minutes.',
      'Serve chicken over rice and spoon extra sauce on top.',
    ],
  },
  {
    id: 102,
    title: 'Cheesy Mushroom Omelette Toast',
    image: 'https://picsum.photos/400/300?random=102',
    readyInMinutes: 15,
    servings: 1,
    missedIngredientCount: 0,
    usedIngredientCount: 5,
    sourceUrl: null,
    ingredients: [
      { name: 'Egg', amount: 2, unit: 'pcs' },
      { name: 'Mushroom', amount: 80, unit: 'g' },
      { name: 'Cheese', amount: 40, unit: 'g' },
      { name: 'Bread', amount: 2, unit: 'slices' },
      { name: 'Olive Oil', amount: 1, unit: 'tsp' },
    ],
    instructions: [
      'Toast bread slices until golden and crisp.',
      'Sauté sliced mushrooms in olive oil for 2-3 minutes.',
      'Beat eggs with a pinch of salt and pour into the pan.',
      'Sprinkle cheese over the eggs, fold omelette, and cook through.',
      'Serve omelette on toast.',
    ],
  },
  {
    id: 103,
    title: 'Tomato Egg Fried Rice',
    image: 'https://picsum.photos/400/300?random=103',
    readyInMinutes: 20,
    servings: 2,
    missedIngredientCount: 0,
    usedIngredientCount: 5,
    sourceUrl: null,
    ingredients: [
      { name: 'Rice', amount: 2, unit: 'cups' },
      { name: 'Egg', amount: 2, unit: 'pcs' },
      { name: 'Tomato', amount: 1, unit: 'pc' },
      { name: 'Onion', amount: 0.5, unit: 'pc' },
      { name: 'Soy Sauce', amount: 1, unit: 'tbsp' },
    ],
    instructions: [
      'Scramble eggs in a hot pan and set aside.',
      'Sauté chopped onion and diced tomato until soft.',
      'Add cooked rice and break up any clumps.',
      'Stir in soy sauce and scrambled eggs, then cook 2 minutes.',
    ],
  },
  {
    id: 104,
    title: 'One-Pan Garlic Chicken Pasta',
    image: 'https://picsum.photos/400/300?random=104',
    readyInMinutes: 35,
    servings: 3,
    missedIngredientCount: 0,
    usedIngredientCount: 5,
    sourceUrl: null,
    ingredients: [
      { name: 'Pasta', amount: 250, unit: 'g' },
      { name: 'Chicken', amount: 220, unit: 'g' },
      { name: 'Garlic', amount: 3, unit: 'cloves' },
      { name: 'Milk', amount: 0.75, unit: 'cup' },
      { name: 'Cheese', amount: 70, unit: 'g' },
    ],
    instructions: [
      'Cook pasta in salted water until al dente, then drain.',
      'Cook chicken strips in a pan with olive oil until done.',
      'Add minced garlic and cook for 30 seconds.',
      'Pour in milk, add pasta and cheese, then stir until creamy.',
      'Season with salt and pepper before serving.',
    ],
  },
  {
    id: 105,
    title: 'Potato Carrot Soy Stir-Fry',
    image: 'https://picsum.photos/400/300?random=105',
    readyInMinutes: 30,
    servings: 2,
    missedIngredientCount: 0,
    usedIngredientCount: 5,
    sourceUrl: null,
    ingredients: [
      { name: 'Potato', amount: 2, unit: 'pcs' },
      { name: 'Carrot', amount: 1, unit: 'pc' },
      { name: 'Onion', amount: 1, unit: 'pc' },
      { name: 'Soy Sauce', amount: 1.5, unit: 'tbsp' },
      { name: 'Olive Oil', amount: 1, unit: 'tbsp' },
    ],
    instructions: [
      'Slice potato and carrot into thin strips.',
      'Heat oil in a pan and sauté onion until fragrant.',
      'Add potato and carrot, stir-frying until tender.',
      'Add soy sauce and a splash of water, then cook 2 more minutes.',
      'Serve hot with rice or bread.',
    ],
  },
  {
    id: 106,
    title: 'Mushroom Bell Pepper Rice Skillet',
    image: 'https://picsum.photos/400/300?random=106',
    readyInMinutes: 22,
    servings: 2,
    missedIngredientCount: 0,
    usedIngredientCount: 5,
    sourceUrl: null,
    ingredients: [
      { name: 'Rice', amount: 2, unit: 'cups' },
      { name: 'Mushroom', amount: 100, unit: 'g' },
      { name: 'Bell Pepper', amount: 1, unit: 'pc' },
      { name: 'Garlic', amount: 2, unit: 'cloves' },
      { name: 'Soy Sauce', amount: 1, unit: 'tbsp' },
    ],
    instructions: [
      'Sauté garlic, mushrooms, and bell pepper in olive oil.',
      'Add cooked rice and stir well to combine.',
      'Season with soy sauce, salt, and pepper.',
      'Cook until heated through and lightly crisped.',
    ],
  },
  {
    id: 107,
    title: 'Chicken Lettuce Wraps',
    image: 'https://picsum.photos/400/300?random=107',
    readyInMinutes: 18,
    servings: 2,
    missedIngredientCount: 0,
    usedIngredientCount: 5,
    sourceUrl: null,
    ingredients: [
      { name: 'Chicken', amount: 200, unit: 'g' },
      { name: 'Lettuce', amount: 8, unit: 'leaves' },
      { name: 'Onion', amount: 0.5, unit: 'pc' },
      { name: 'Cucumber', amount: 0.5, unit: 'pc' },
      { name: 'Soy Sauce', amount: 1.5, unit: 'tbsp' },
    ],
    instructions: [
      'Cook minced chicken with chopped onion in a pan.',
      'Add soy sauce and cook until liquid reduces.',
      'Slice cucumber thinly and wash lettuce leaves.',
      'Spoon chicken mixture into lettuce leaves and top with cucumber.',
    ],
  },
  {
    id: 108,
    title: 'Tomato Cheese Open Sandwich',
    image: 'https://picsum.photos/400/300?random=108',
    readyInMinutes: 12,
    servings: 1,
    missedIngredientCount: 0,
    usedIngredientCount: 5,
    sourceUrl: null,
    ingredients: [
      { name: 'Bread', amount: 2, unit: 'slices' },
      { name: 'Tomato', amount: 1, unit: 'pc' },
      { name: 'Cheese', amount: 50, unit: 'g' },
      { name: 'Olive Oil', amount: 1, unit: 'tsp' },
      { name: 'Pepper', amount: 0.25, unit: 'tsp' },
    ],
    instructions: [
      'Lightly brush bread with olive oil.',
      'Top with tomato slices and grated cheese.',
      'Toast in a pan or oven until cheese melts.',
      'Finish with black pepper and serve warm.',
    ],
  },
];

export const INGREDIENT_LIST: string[] = [
  'Chicken',
  'Egg',
  'Rice',
  'Pasta',
  'Onion',
  'Garlic',
  'Tomato',
  'Potato',
  'Carrot',
  'Soy Sauce',
  'Olive Oil',
  'Salt',
  'Pepper',
  'Cheese',
  'Milk',
  'Bread',
  'Lettuce',
  'Cucumber',
  'Bell Pepper',
  'Mushroom',
];

export const MOCK_USER: MockUser = {
  username: 'YasuoChef',
  avatarUrl: 'https://i.pravatar.cc/150?img=33',
  preferences: {
    isVegetarian: false,
    isHalal: false,
    darkMode: false,
  },
};
